%% initialize_check_strings.m
% initialize check strings for all babies data
%
% s = ' ';  equals = '='; less = '<'; greater = '>';
% str_min = 'minimum';  str_max = 'maximum';  str_rows = 'rows';  str_length = 'length';
% str_land = 'land';  str_ipop = 'IPOP';  str_ngen = 'NGEN';  str_op = 'overpop';
% str_limit = 'limit';  
% str_p = 'population';  
% str_tx = 'trace_x'; 
% str_ty = 'trace_y';  
% str_tcs = 'trace_cluster_seed'; 
% str_sd = 'seed_distances';  
% str_par = 'parents';  
% str_k = 'kills';  
% str_r = 'rivalries';  
% str_nc = 'num_clusters';  
% str_tc = 'trace_cluster'; 
% str_onc = 'orgsncluster'; 
% str_cx = 'centroid_x';  
% str_cy = 'centroid_y';  
% str_div = 'cluster_diversity';  
% str_dia = 'cluster_diameters';  
% str_gr = 'gryation_radii';
% str_pl = 'path_length'; 
% str_nd = 'num_descendants'; 
% str_ndc = 'num_descendant_clusters';  
% str_dc = 'descendant_clusters'; 
% str_ncp = 'num_clusters_produced';  
% str_cp = 'clusters_produced'; 
% str_ncf = 'num_clusters_fused';
% str_cf = 'clusters_fused'; 
global s str_min str_max str_rows str_cols str_length str_land str_op str_ini;
s = ' ';  equals = '='; less = '<'; greater = '>';  gte = [greater equals]; lte = [less equals];
str_min = 'minimum';  str_max = 'maximum';  str_rows = 'rows';  str_cols = 'cols';
str_length = 'length';  str_land = 'land';  str_op = 'overpop'; str_ini = 'initial';
str_limit = 'limit';  
str_p = 'population';  
str_tx = 'trace_x'; 
str_ty = 'trace_y';  
str_tcs = 'trace_cluster_seed'; 
str_sd = 'seed_distances';  
str_par = 'parents';  
str_k = 'kills';  
str_r = 'rivalries';  
str_nc = 'num_clusters';  
str_tc = 'trace_cluster'; 
str_onc = 'orgsnclusters'; 
str_cx = 'centroid_x';  
str_cy = 'centroid_y';  
str_div = 'cluster_diversity';  
str_dia = 'cluster_diameters';  
str_gr = 'gyration_radii';
str_pl = 'path_length'; 
str_nd = 'num_descendants'; 
str_ndc = 'num_descendant_clusters';  
str_dc = 'descendant_clusters'; 
str_ncp = 'num_clusters_produced';  
str_cp = 'clusters_produced'; 
str_ncf = 'num_clusters_fused';
str_cf = 'clusters_fused'; 